
-- 1. Create the table if it doesn't exist at all
CREATE TABLE IF NOT EXISTS public.movies (
  id TEXT PRIMARY KEY
);

-- 2. Add any missing columns
ALTER TABLE public.movies ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE public.movies ADD COLUMN IF NOT EXISTS thumbnail TEXT;
ALTER TABLE public.movies ADD COLUMN IF NOT EXISTS banner TEXT;
ALTER TABLE public.movies ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE public.movies ADD COLUMN IF NOT EXISTS rating TEXT;
ALTER TABLE public.movies ADD COLUMN IF NOT EXISTS year INTEGER;
ALTER TABLE public.movies ADD COLUMN IF NOT EXISTS duration TEXT;
ALTER TABLE public.movies ADD COLUMN IF NOT EXISTS genre TEXT[];
ALTER TABLE public.movies ADD COLUMN IF NOT EXISTS "ageRating" TEXT;
ALTER TABLE public.movies ADD COLUMN IF NOT EXISTS "contentWarnings" TEXT[];
ALTER TABLE public.movies ADD COLUMN IF NOT EXISTS "isOriginal" BOOLEAN DEFAULT false;
ALTER TABLE public.movies ADD COLUMN IF NOT EXISTS progress NUMERIC;
ALTER TABLE public.movies ADD COLUMN IF NOT EXISTS "desktopOnly" BOOLEAN DEFAULT false;
ALTER TABLE public.movies ADD COLUMN IF NOT EXISTS "streamStatus" TEXT;
ALTER TABLE public.movies ADD COLUMN IF NOT EXISTS quality TEXT;
ALTER TABLE public.movies ADD COLUMN IF NOT EXISTS "mobileThumbnail" TEXT;
ALTER TABLE public.movies ADD COLUMN IF NOT EXISTS "mobileBanner" TEXT;
ALTER TABLE public.movies ADD COLUMN IF NOT EXISTS "cardBanner" TEXT;
ALTER TABLE public.movies ADD COLUMN IF NOT EXISTS "mobileCardBanner" TEXT;
ALTER TABLE public.movies ADD COLUMN IF NOT EXISTS logo TEXT;
ALTER TABLE public.movies ADD COLUMN IF NOT EXISTS "videoUrl" TEXT;
ALTER TABLE public.movies ADD COLUMN IF NOT EXISTS "detailMobileBanner" TEXT;
ALTER TABLE public.movies ADD COLUMN IF NOT EXISTS "detailBanner" TEXT;
ALTER TABLE public.movies ADD COLUMN IF NOT EXISTS "mobileCarouselBanner" TEXT;
ALTER TABLE public.movies ADD COLUMN IF NOT EXISTS subtitles JSONB;
ALTER TABLE public.movies ADD COLUMN IF NOT EXISTS "trailerUrl" TEXT;
ALTER TABLE public.movies ADD COLUMN IF NOT EXISTS "trailerVttUrl" TEXT;
ALTER TABLE public.movies ADD COLUMN IF NOT EXISTS "spriteUrl" TEXT;
ALTER TABLE public.movies ADD COLUMN IF NOT EXISTS "spriteConfig" JSONB;
ALTER TABLE public.movies ADD COLUMN IF NOT EXISTS "downloadUrl" TEXT;
ALTER TABLE public.movies ADD COLUMN IF NOT EXISTS seasons JSONB;
ALTER TABLE public.movies ADD COLUMN IF NOT EXISTS "squareThumbnail" TEXT;
ALTER TABLE public.movies ADD COLUMN IF NOT EXISTS "tallTrailerUrl" TEXT;
ALTER TABLE public.movies ADD COLUMN IF NOT EXISTS "mediaType" TEXT DEFAULT 'movie';
ALTER TABLE public.movies ADD COLUMN IF NOT EXISTS "xRay" JSONB;
ALTER TABLE public.movies ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();


INSERT INTO movies (
  id, title, thumbnail, banner, description, rating, year, duration, genre, 
  "ageRating", "contentWarnings", "isOriginal", progress, "desktopOnly", 
  "streamStatus", quality, "mobileThumbnail", "mobileBanner", "cardBanner", 
  "mobileCardBanner", logo, "videoUrl", "detailMobileBanner", "detailBanner", 
  "mobileCarouselBanner", subtitles, "trailerUrl", "trailerVttUrl", "spriteUrl", 
  "spriteConfig", "downloadUrl", seasons, "squareThumbnail", "tallTrailerUrl", 
  "mediaType", "xRay"
) VALUES (
  'ang-huling-el-bimbo-play',
  'Ang Huling El Bimbo Play',
  '/images/el-bimbo.webp',
  '/images/el-bimbo-banner.jpg',
  'A nostalgic journey through the 90s, where three friends find themselves at a crossroads that will change their lives forever.',
  '9.8',
  2026,
  '49m',
  ARRAY['Musical', 'Drama', 'Nostalgia'],
  'PG-13',
  ARRAY['mature themes', 'language', 'violence', 'alcohol use'],
  true,
  null,
  false,
  null,
  null,
  '/images/el-bimbo-mobile.webp',
  '/images/el-bimbo-mobile.webp',
  '/images/el-bimbo.webp',
  '/images/el-bimbo.webp',
  '/images/el-bimbo-logo.webp',
  'https://boycanad.github.io/stream-storage-1/new_index.m3u8',
  '/images/el-bimbo-detail-mobile.webp',
  '/images/el-bimbo-detail.webp',
  '/images/el-bimbo-mobile-carousel.jpg',
  '[{"label":"Filipino","srclang":"fil","url":"https://boycanad.github.io/stream-storage-1/AngHulingElBimboPlay.vtt"},{"label":"English","srclang":"en","url":"https://boycanad.github.io/stream-storage-1/AngHulingElBimboPlayEnglish.vtt"},{"label":"Karaoke","srclang":"fil","url":"https://figlafktafkwzmgeyslw.supabase.co/storage/v1/object/public/Offline/(KARAOKE)AngHulingElBimboPlay.vtt"}]',
  'https://boycanad.github.io/stream-storage-1/trailer.mp4',
  null,
  '/images/storyboards/sprite_5s_hq_synced.jpg',
  '{"rows":30,"cols":20,"interval":5,"thumbWidth":320,"thumbHeight":180}',
  'https://video-proxy.booran-special.workers.dev/',
  null,
  '/images/clips/square/AngHulingElBimboPlay.webp',
  'https://res.cloudinary.com/dtzphltjc/video/upload/f_mp4,vc_h264,ac_aac/v1776811392/HulingElBimboPlay-tall_v5itkx.mp4',
  'movie',
  null
) ON CONFLICT (id) DO UPDATE SET 
  title = EXCLUDED.title,
  thumbnail = EXCLUDED.thumbnail,
  banner = EXCLUDED.banner,
  description = EXCLUDED.description,
  rating = EXCLUDED.rating,
  year = EXCLUDED.year,
  duration = EXCLUDED.duration,
  genre = EXCLUDED.genre,
  "ageRating" = EXCLUDED."ageRating",
  "contentWarnings" = EXCLUDED."contentWarnings",
  "isOriginal" = EXCLUDED."isOriginal",
  progress = EXCLUDED.progress,
  "desktopOnly" = EXCLUDED."desktopOnly",
  "streamStatus" = EXCLUDED."streamStatus",
  quality = EXCLUDED.quality,
  "mobileThumbnail" = EXCLUDED."mobileThumbnail",
  "mobileBanner" = EXCLUDED."mobileBanner",
  "cardBanner" = EXCLUDED."cardBanner",
  "mobileCardBanner" = EXCLUDED."mobileCardBanner",
  logo = EXCLUDED.logo,
  "videoUrl" = EXCLUDED."videoUrl",
  "detailMobileBanner" = EXCLUDED."detailMobileBanner",
  "detailBanner" = EXCLUDED."detailBanner",
  "mobileCarouselBanner" = EXCLUDED."mobileCarouselBanner",
  subtitles = EXCLUDED.subtitles,
  "trailerUrl" = EXCLUDED."trailerUrl",
  "trailerVttUrl" = EXCLUDED."trailerVttUrl",
  "spriteUrl" = EXCLUDED."spriteUrl",
  "spriteConfig" = EXCLUDED."spriteConfig",
  "downloadUrl" = EXCLUDED."downloadUrl",
  seasons = EXCLUDED.seasons,
  "squareThumbnail" = EXCLUDED."squareThumbnail",
  "tallTrailerUrl" = EXCLUDED."tallTrailerUrl",
  "mediaType" = EXCLUDED."mediaType",
  "xRay" = EXCLUDED."xRay";


INSERT INTO movies (
  id, title, thumbnail, banner, description, rating, year, duration, genre, 
  "ageRating", "contentWarnings", "isOriginal", progress, "desktopOnly", 
  "streamStatus", quality, "mobileThumbnail", "mobileBanner", "cardBanner", 
  "mobileCardBanner", logo, "videoUrl", "detailMobileBanner", "detailBanner", 
  "mobileCarouselBanner", subtitles, "trailerUrl", "trailerVttUrl", "spriteUrl", 
  "spriteConfig", "downloadUrl", seasons, "squareThumbnail", "tallTrailerUrl", 
  "mediaType", "xRay"
) VALUES (
  'ang-huling-el-bimbo-play-xray',
  'Ang Huling El Bimbo Play - Bonus X-Ray Edition',
  '/images/el-bimbo-x-ray.webp',
  '/images/el-bimbo-x-ray.webp',
  'The same nostalgic journey through the 90s, now with the X-Ray bonus experience — explore behind-the-scenes cast info and songs as you watch.',
  '9.8',
  2026,
  '49m',
  ARRAY['Musical', 'Drama', 'Nostalgia', 'X-Ray'],
  'PG-13',
  ARRAY['mature themes', 'language', 'violence', 'alcohol use'],
  true,
  null,
  false,
  null,
  null,
  '/images/el-bimbo-mobile.webp',
  '/images/el-bimbo-x-ray.webp',
  '/images/el-bimbo-x-ray.webp',
  '/images/el-bimbo-x-ray.webp',
  '/images/el-bimbo-x-ray-logo.webp',
  'https://boycanad.github.io/stream-storage-1/new_index.m3u8',
  '/images/el-bimbo-detail-mobile.webp',
  '/images/el-bimbo-detail.webp',
  '/images/el-bimbo-mobile-carousel.jpg',
  '[{"label":"Filipino","srclang":"fil","url":"https://boycanad.github.io/stream-storage-1/AngHulingElBimboPlay.vtt"},{"label":"English","srclang":"en","url":"https://boycanad.github.io/stream-storage-1/AngHulingElBimboPlayEnglish.vtt"},{"label":"Karaoke","srclang":"fil","url":"https://figlafktafkwzmgeyslw.supabase.co/storage/v1/object/public/Offline/(KARAOKE)AngHulingElBimboPlay.vtt"}]',
  'https://boycanad.github.io/stream-storage-1/trailer.mp4',
  null,
  '/images/storyboards/sprite_5s_hq_synced.jpg',
  '{"rows":30,"cols":20,"interval":5,"thumbWidth":320,"thumbHeight":180}',
  'https://video-proxy.booran-special.workers.dev/',
  null,
  '/images/clips/square/AngHulingElBimboPlay.webp',
  'https://res.cloudinary.com/dtzphltjc/video/upload/f_mp4,vc_h264,ac_aac/v1776811392/HulingElBimboPlay-tall_v5itkx.mp4',
  'movie',
  '{"scenes":[{"start":11,"end":349,"songs":[{"title":"Ang Huling El Bimbo Orchestral Arrangement","artist":"Eraserheads","start":11,"end":52},{"title":"Minsan","artist":"Eraserheads","start":52,"end":349}],"actors":[{"name":"Dancers","character":"Ensemble","image":"/images/xray/dancers.jpg","timeRanges":[{"start":52,"end":349}]},{"name":"Merv Pring","character":"Marco","image":"/images/xray/marco-xray.webp","timeRanges":[{"start":64,"end":349}]},{"name":"Edrian Lee Catalan","character":"Edrian","image":"/images/xray/edrian-xray.webp","timeRanges":[{"start":79,"end":349}]},{"name":"Lance Dominguez","character":"Pok","image":"/images/xray/pok-xray.webp","timeRanges":[{"start":97,"end":349}]},{"name":"Jan Xian Castro","character":"Xian","image":"/images/xray/xian-xray.webp","timeRanges":[{"start":97,"end":349}]},{"name":"Rich Ann Capuli","character":"Joy","image":"/images/xray/joy-xray.webp","timeRanges":[{"start":165,"end":349}]}],"trivia":[{"text":"Fun Fact: Every sound you hear is a digital playback. The entire theater audio is actually pre-recorded for a flawless, studio-quality performance.","start":140,"end":160}]},{"start":358,"end":709,"songs":[{"title":"Tindahan ni Aling Nena","artist":"Eraserheads","start":359,"end":553}],"actors":[{"name":"Aisha Dela Cruz","character":"Marco''s Mother","image":"/images/xray/aisha-xray.webp","timeRanges":[{"start":358,"end":557}]},{"name":"Merv Pring","character":"Marco","image":"/images/xray/marco-xray.webp","timeRanges":[{"start":358,"end":709}]},{"name":"Dancers","character":"Ensemble","image":"/images/xray/dancers.jpg","timeRanges":[{"start":358,"end":557}]},{"name":"Mark Jerzel Tria","character":"Jazzy","image":"/images/xray/jazzy-xray.webp","timeRanges":[{"start":358,"end":709}]},{"name":"Juliana Faith Cordovez","character":"Aling Nena","image":"/images/xray/nena-xray.webp","timeRanges":[{"start":369,"end":709}]},{"name":"Rich Ann Capuli","character":"Joy","image":"/images/xray/joy-xray.webp","timeRanges":[{"start":384,"end":709}]},{"name":"Edrian Lee Catalan","character":"Edrian","image":"/images/xray/edrian-xray.webp","timeRanges":[{"start":447,"end":709}]},{"name":"Lance Dominguez","character":"Pok","image":"/images/xray/pok-xray.webp","timeRanges":[{"start":447,"end":709}]},{"name":"Jan Xian Castro","character":"Xian","image":"/images/xray/xian-xray.webp","timeRanges":[{"start":447,"end":709}]}],"trivia":[{"text":"Fun Fact: The moment where the three friends grab and destroy Aling Nena''s store was completely unplanned and unscripted.","start":644,"end":664}]},{"start":726,"end":1072,"songs":[{"title":"Overdrive Acapella","artist":"Eraserheads","start":789,"end":831},{"title":"Alapaap/Overdrive","artist":"Eraserheads","start":836,"end":1041}],"actors":[{"name":"Jan Xian Castro","character":"Xian","image":"/images/xray/xian-xray.webp","timeRanges":[{"start":726,"end":1072}]},{"name":"Lance Dominguez","character":"Pok","image":"/images/xray/pok-xray.webp","timeRanges":[{"start":726,"end":1072}]},{"name":"Edrian Lee Catalan","character":"Edrian","image":"/images/xray/edrian-xray.webp","timeRanges":[{"start":726,"end":1072}]},{"name":"Rich Ann Capuli","character":"Joy","image":"/images/xray/joy-xray.webp","timeRanges":[{"start":733,"end":1072}]},{"name":"Mark Jerzel Tria","character":"Jazzy","image":"/images/xray/jazzy-xray.webp","timeRanges":[{"start":733,"end":1072}]},{"name":"Merv Pring","character":"Marco","image":"/images/xray/marco-xray.webp","timeRanges":[{"start":759,"end":1072}]}],"trivia":[{"text":"Trivia: Did you know? Some character voices are actually provided by other actors who filled in when the original performers were absent during the recording session.","start":730,"end":750},{"text":"Trivia: Did you know? The music production and recording sessions were completed in just 4 to 5 days.","start":974,"end":994}],"polls":[{"question":"Who in the Barkada is your most favorite?","options":["Marco","Joy","Pok","Xian","Edrian"],"start":920,"end":940}]},{"start":1079,"end":1249,"songs":[{"title":"Spoliarium","artist":"Eraserheads","start":1120,"end":1249}],"actors":[{"name":"Merv Pring","character":"Marco","image":"/images/xray/marco-xray.webp","timeRanges":[{"start":1079,"end":1099}]},{"name":"Rich Ann Capuli","character":"Joy","image":"/images/xray/joy-xray.webp","timeRanges":[{"start":1079,"end":1228}]},{"name":"Lance Dominguez","character":"Pok","image":"/images/xray/pok-xray.webp","timeRanges":[{"start":1079,"end":1170}]},{"name":"Jan Xian Castro","character":"Xian","image":"/images/xray/xian-xray.webp","timeRanges":[{"start":1079,"end":1099}]},{"name":"Edrian Lee Catalan","character":"Edrian","image":"/images/xray/edrian-xray.webp","timeRanges":[{"start":1079,"end":1099}]}],"trivia":[{"text":"Trivia: Did you know? This entire theater performance was filmed by only three people and edited by just one person.","start":1169,"end":1189}]},{"start":1252,"end":1407,"songs":[{"title":"Minsan Instrumental","artist":"Eraserheads","start":1252,"end":1314}],"actors":[{"name":"Lance Dominguez","character":"Pok","image":"/images/xray/pok-xray.webp","timeRanges":[{"start":1252,"end":1321}]},{"name":"Mark Jerzel Tria","character":"Jazzy","image":"/images/xray/jazzy-xray.webp","timeRanges":[{"start":1260,"end":1321},{"start":1362,"end":1407}]},{"name":"Edrian Lee Catalan","character":"Edrian","image":"/images/xray/edrian-xray.webp","timeRanges":[{"start":1260,"end":1321}]},{"name":"Jan Xian Castro","character":"Xian","image":"/images/xray/xian-xray.webp","timeRanges":[{"start":1280,"end":1321}]},{"name":"Merv Pring","character":"Marco","image":"/images/xray/marco-xray.webp","timeRanges":[{"start":1284,"end":1360}]},{"name":"Rich Ann Capuli","character":"Joy","image":"/images/xray/joy-xray.webp","timeRanges":[{"start":1284,"end":1407}]}]},{"start":1413,"end":1809,"songs":[{"title":"Pare Ko/Yoko","artist":"Eraserheads","start":1420,"end":1759}],"actors":[{"name":"Dancers","character":"Ensemble","image":"/images/xray/dancers.jpg","timeRanges":[{"start":1413,"end":1762}]},{"name":"Merv Pring","character":"Marco","image":"/images/xray/marco-xray.webp","timeRanges":[{"start":1489,"end":1809}]},{"name":"Jan Xian Castro","character":"Xian","image":"/images/xray/xian-xray.webp","timeRanges":[{"start":1523,"end":1556},{"start":1673,"end":1687},{"start":1763,"end":1809}]},{"name":"Edrian Lee Catalan","character":"Edrian","image":"/images/xray/edrian-xray.webp","timeRanges":[{"start":1673,"end":1687},{"start":1763,"end":1809}]}],"trivia":[{"text":"Trivia: Did you know? Some of the songs Marco sings were actually recorded by Edrian because Marco was dealing with vocal injuries during the session.","start":1493,"end":1513}]},{"start":1815,"end":1841,"songs":[{"title":"Burnout (Slowed)","artist":"Eraserheads","start":1821,"end":1841}],"actors":[{"name":"Merv Pring","character":"Marco","image":"/images/xray/marco-xray.webp","timeRanges":[{"start":1815,"end":1841}]},{"name":"Edrian Lee Catalan","character":"Edrian","image":"/images/xray/edrian-xray.webp","timeRanges":[{"start":1821,"end":1841}]}]},{"start":1853,"end":2043,"songs":[{"title":"Tama Ka/Ligaya","artist":"Eraserheads","start":1853,"end":2043}],"actors":[{"name":"Merv Pring","character":"Marco","image":"/images/xray/marco-xray.webp","timeRanges":[{"start":1857,"end":2005}]},{"name":"Rich Ann Capuli","character":"Joy","image":"/images/xray/joy-xray.webp","timeRanges":[{"start":1860,"end":2043}]},{"name":"Juliana Faith Cordovez","character":"Aling Nena","image":"/images/xray/nena-xray.webp","timeRanges":[{"start":1868,"end":2005}]},{"name":"Dancers","character":"Ensemble","image":"/images/xray/dancers.jpg","timeRanges":[{"start":2005,"end":2043}]}],"trivia":[{"text":"Fun Fact: Ang Huling El Bimbo Play was the very first production to perform at Teatro Bonifacio.","start":1941,"end":1961}]},{"start":2044,"end":2244,"songs":[{"title":"Ang Huling El Bimbo (Violin & Piano)","artist":"Eraserheads","start":2184,"end":2214}],"actors":[{"name":"Merv Pring","character":"Marco","image":"/images/xray/marco-xray.webp","timeRanges":[{"start":2044,"end":2109},{"start":2171,"end":2204}]},{"name":"Lance Dominguez","character":"Pok","image":"/images/xray/pok-xray.webp","timeRanges":[{"start":2045,"end":2091},{"start":2132,"end":2186}]},{"name":"Aisha Dela Cruz","character":"Marco''s Mother","image":"/images/xray/aisha-xray.webp","timeRanges":[{"start":2052,"end":2109},{"start":2214,"end":2244}]},{"name":"Rich Ann Capuli","character":"Joy","image":"/images/xray/joy-xray.webp","timeRanges":[{"start":2117,"end":2204}]},{"name":"Ahlysson Dela Cruz","character":"Doctor","image":"/images/xray/ahlysson-delacruz.jpg","timeRanges":[{"start":2214,"end":2233}]}]},{"start":2245,"end":2795,"songs":[{"title":"Ang Huling El Bimbo","artist":"Eraserheads","start":2255,"end":2786}],"actors":[{"name":"Merv Pring","character":"Marco","image":"/images/xray/marco-xray.webp","timeRanges":[{"start":2245,"end":2795}]},{"name":"Dancers","character":"Ensemble","image":"/images/xray/dancers.jpg","timeRanges":[{"start":2255,"end":2389},{"start":2469,"end":2706},{"start":2730,"end":2795}]},{"name":"Lance Dominguez","character":"Pok","image":"/images/xray/pok-xray.webp","timeRanges":[{"start":2255,"end":2389},{"start":2756,"end":2795}]},{"name":"Edrian Lee Catalan","character":"Edrian","image":"/images/xray/edrian-xray.webp","timeRanges":[{"start":2255,"end":2389},{"start":2756,"end":2795}]},{"name":"Aisha Dela Cruz","character":"Marco''s Mother","image":"/images/xray/aisha-xray.webp","timeRanges":[{"start":2255,"end":2389}]},{"name":"Rich Ann Capuli","character":"Joy","image":"/images/xray/joy-xray.webp","timeRanges":[{"start":2440,"end":2795}]},{"name":"Jan Xian Castro","character":"Xian","image":"/images/xray/xian-xray.webp","timeRanges":[{"start":2756,"end":2795}]},{"name":"Juliana Faith Cordovez","character":"Aling Nena","image":"/images/xray/nena-xray.webp","timeRanges":[{"start":2756,"end":2795}]}],"trivia":[{"text":"Fun Fact: The entire choreography was finalized just days before the actual performance.","start":2477,"end":2497},{"text":"Fun Fact: The girls with white strings were originally supposed to appear in this scene, but they were left out by mistake and the production ultimately chose not to include them.","start":2679,"end":2699},{"text":"Trivia: Did you know? Merv Pring is the one who choreographed the entire performance.","start":2735,"end":2755}],"polls":[{"question":"Which song is your favorite throughout the entire theater performance?","options":["Minsan","Tindahan ni Aling Nena","Alapaap/Overdrive","Spoliarium","Pare Ko","Tama Ka/Ligaya","Ang Huling El Bimbo"],"start":2782,"end":2802}]},{"start":2799,"end":2980,"songs":[{"title":"Ang Huling El Bimbo Orchestral Arrangement","artist":"Eraserheads","start":2799,"end":2980}],"actors":[],"polls":[{"question":"Which song is your favorite throughout the entire theater performance?","options":["Minsan","Tindahan ni Aling Nena","Alapaap/Overdrive","Spoliarium","Pare Ko","Tama Ka/Ligaya","Ang Huling El Bimbo"],"start":2782,"end":2802}]}]}'
) ON CONFLICT (id) DO UPDATE SET 
  title = EXCLUDED.title,
  thumbnail = EXCLUDED.thumbnail,
  banner = EXCLUDED.banner,
  description = EXCLUDED.description,
  rating = EXCLUDED.rating,
  year = EXCLUDED.year,
  duration = EXCLUDED.duration,
  genre = EXCLUDED.genre,
  "ageRating" = EXCLUDED."ageRating",
  "contentWarnings" = EXCLUDED."contentWarnings",
  "isOriginal" = EXCLUDED."isOriginal",
  progress = EXCLUDED.progress,
  "desktopOnly" = EXCLUDED."desktopOnly",
  "streamStatus" = EXCLUDED."streamStatus",
  quality = EXCLUDED.quality,
  "mobileThumbnail" = EXCLUDED."mobileThumbnail",
  "mobileBanner" = EXCLUDED."mobileBanner",
  "cardBanner" = EXCLUDED."cardBanner",
  "mobileCardBanner" = EXCLUDED."mobileCardBanner",
  logo = EXCLUDED.logo,
  "videoUrl" = EXCLUDED."videoUrl",
  "detailMobileBanner" = EXCLUDED."detailMobileBanner",
  "detailBanner" = EXCLUDED."detailBanner",
  "mobileCarouselBanner" = EXCLUDED."mobileCarouselBanner",
  subtitles = EXCLUDED.subtitles,
  "trailerUrl" = EXCLUDED."trailerUrl",
  "trailerVttUrl" = EXCLUDED."trailerVttUrl",
  "spriteUrl" = EXCLUDED."spriteUrl",
  "spriteConfig" = EXCLUDED."spriteConfig",
  "downloadUrl" = EXCLUDED."downloadUrl",
  seasons = EXCLUDED.seasons,
  "squareThumbnail" = EXCLUDED."squareThumbnail",
  "tallTrailerUrl" = EXCLUDED."tallTrailerUrl",
  "mediaType" = EXCLUDED."mediaType",
  "xRay" = EXCLUDED."xRay";


INSERT INTO movies (
  id, title, thumbnail, banner, description, rating, year, duration, genre, 
  "ageRating", "contentWarnings", "isOriginal", progress, "desktopOnly", 
  "streamStatus", quality, "mobileThumbnail", "mobileBanner", "cardBanner", 
  "mobileCardBanner", logo, "videoUrl", "detailMobileBanner", "detailBanner", 
  "mobileCarouselBanner", subtitles, "trailerUrl", "trailerVttUrl", "spriteUrl", 
  "spriteConfig", "downloadUrl", seasons, "squareThumbnail", "tallTrailerUrl", 
  "mediaType", "xRay"
) VALUES (
  'minsan',
  'Minsan',
  '/images/minsan.webp',
  '/images/minsan-banner.webp',
  '“Minsan” is a heartfelt reflection on friendship, nostalgia, and the bittersweet passage of time. It tells the story of people who once shared deep connections and carefree moments, only to drift apart as life moves forward.',
  '9.5',
  2026,
  '5m',
  ARRAY['Musical', 'Drama', 'Nostalgia', 'Ang Huling El Bimbo'],
  'PG-13',
  null,
  false,
  null,
  false,
  null,
  null,
  null,
  '/images/minsan-detail-mobile.webp',
  '/images/minsan.webp',
  null,
  '/images/minsan-logo.webp',
  'https://boycanad.github.io/stream-storage-3/index.m3u8',
  null,
  null,
  '/images/minsan-mobile-carousel.webp',
  null,
  'https://boycanad.github.io/stream-storage-2/MINSAN_TRAILER_MOBILE.mp4',
  'https://boycanad.github.io/stream-storage-2/TRAILER.vtt',
  null,
  null,
  null,
  null,
  '/images/clips/square/Minsan.webp',
  'https://res.cloudinary.com/dtzphltjc/video/upload/f_mp4,vc_h264,ac_aac/v1776811369/Minsan-tall_etknbw.mp4',
  'movie',
  null
) ON CONFLICT (id) DO UPDATE SET 
  title = EXCLUDED.title,
  thumbnail = EXCLUDED.thumbnail,
  banner = EXCLUDED.banner,
  description = EXCLUDED.description,
  rating = EXCLUDED.rating,
  year = EXCLUDED.year,
  duration = EXCLUDED.duration,
  genre = EXCLUDED.genre,
  "ageRating" = EXCLUDED."ageRating",
  "contentWarnings" = EXCLUDED."contentWarnings",
  "isOriginal" = EXCLUDED."isOriginal",
  progress = EXCLUDED.progress,
  "desktopOnly" = EXCLUDED."desktopOnly",
  "streamStatus" = EXCLUDED."streamStatus",
  quality = EXCLUDED.quality,
  "mobileThumbnail" = EXCLUDED."mobileThumbnail",
  "mobileBanner" = EXCLUDED."mobileBanner",
  "cardBanner" = EXCLUDED."cardBanner",
  "mobileCardBanner" = EXCLUDED."mobileCardBanner",
  logo = EXCLUDED.logo,
  "videoUrl" = EXCLUDED."videoUrl",
  "detailMobileBanner" = EXCLUDED."detailMobileBanner",
  "detailBanner" = EXCLUDED."detailBanner",
  "mobileCarouselBanner" = EXCLUDED."mobileCarouselBanner",
  subtitles = EXCLUDED.subtitles,
  "trailerUrl" = EXCLUDED."trailerUrl",
  "trailerVttUrl" = EXCLUDED."trailerVttUrl",
  "spriteUrl" = EXCLUDED."spriteUrl",
  "spriteConfig" = EXCLUDED."spriteConfig",
  "downloadUrl" = EXCLUDED."downloadUrl",
  seasons = EXCLUDED.seasons,
  "squareThumbnail" = EXCLUDED."squareThumbnail",
  "tallTrailerUrl" = EXCLUDED."tallTrailerUrl",
  "mediaType" = EXCLUDED."mediaType",
  "xRay" = EXCLUDED."xRay";


INSERT INTO movies (
  id, title, thumbnail, banner, description, rating, year, duration, genre, 
  "ageRating", "contentWarnings", "isOriginal", progress, "desktopOnly", 
  "streamStatus", quality, "mobileThumbnail", "mobileBanner", "cardBanner", 
  "mobileCardBanner", logo, "videoUrl", "detailMobileBanner", "detailBanner", 
  "mobileCarouselBanner", subtitles, "trailerUrl", "trailerVttUrl", "spriteUrl", 
  "spriteConfig", "downloadUrl", seasons, "squareThumbnail", "tallTrailerUrl", 
  "mediaType", "xRay"
) VALUES (
  'tindahan-ni-aling-nena',
  'Tindahan ni Aling Nena',
  '/images/tindahan.webp',
  '/images/tindahan-detail.webp',
  'A lively and colorful performance of “Tindahan ni Aling Nena” from Ang Huling El Bimbo, this scene brings energy and humor while subtly reflecting the group’s youthful bond and everyday life.',
  '9.7',
  2026,
  '5m',
  ARRAY['Musical', 'Drama', 'Nostalgia', 'Ang Huling El Bimbo'],
  'PG-13',
  null,
  false,
  null,
  false,
  null,
  null,
  null,
  '/images/tindahan-detail-mobile.webp',
  '/images/tindahan.webp',
  null,
  '/images/tindahan-logo.webp',
  'https://boycanad.github.io/stream-storage-3/Tindahan/index.m3u8',
  null,
  null,
  '/images/Tindahan-mobile-banner.webp',
  null,
  'https://boycanad.github.io/stream-storage-2/Tindahan_TRAILER_MOBILE.mp4',
  'https://boycanad.github.io/stream-storage-2/Tindahan_TRAILER_MOBILE.vtt',
  null,
  null,
  null,
  null,
  '/images/clips/square/Tindahan.webp',
  'https://res.cloudinary.com/dtzphltjc/video/upload/f_mp4,vc_h264,ac_aac/v1776811310/Tindahan-tall_jxtnzf.mp4',
  'movie',
  null
) ON CONFLICT (id) DO UPDATE SET 
  title = EXCLUDED.title,
  thumbnail = EXCLUDED.thumbnail,
  banner = EXCLUDED.banner,
  description = EXCLUDED.description,
  rating = EXCLUDED.rating,
  year = EXCLUDED.year,
  duration = EXCLUDED.duration,
  genre = EXCLUDED.genre,
  "ageRating" = EXCLUDED."ageRating",
  "contentWarnings" = EXCLUDED."contentWarnings",
  "isOriginal" = EXCLUDED."isOriginal",
  progress = EXCLUDED.progress,
  "desktopOnly" = EXCLUDED."desktopOnly",
  "streamStatus" = EXCLUDED."streamStatus",
  quality = EXCLUDED.quality,
  "mobileThumbnail" = EXCLUDED."mobileThumbnail",
  "mobileBanner" = EXCLUDED."mobileBanner",
  "cardBanner" = EXCLUDED."cardBanner",
  "mobileCardBanner" = EXCLUDED."mobileCardBanner",
  logo = EXCLUDED.logo,
  "videoUrl" = EXCLUDED."videoUrl",
  "detailMobileBanner" = EXCLUDED."detailMobileBanner",
  "detailBanner" = EXCLUDED."detailBanner",
  "mobileCarouselBanner" = EXCLUDED."mobileCarouselBanner",
  subtitles = EXCLUDED.subtitles,
  "trailerUrl" = EXCLUDED."trailerUrl",
  "trailerVttUrl" = EXCLUDED."trailerVttUrl",
  "spriteUrl" = EXCLUDED."spriteUrl",
  "spriteConfig" = EXCLUDED."spriteConfig",
  "downloadUrl" = EXCLUDED."downloadUrl",
  seasons = EXCLUDED.seasons,
  "squareThumbnail" = EXCLUDED."squareThumbnail",
  "tallTrailerUrl" = EXCLUDED."tallTrailerUrl",
  "mediaType" = EXCLUDED."mediaType",
  "xRay" = EXCLUDED."xRay";


INSERT INTO movies (
  id, title, thumbnail, banner, description, rating, year, duration, genre, 
  "ageRating", "contentWarnings", "isOriginal", progress, "desktopOnly", 
  "streamStatus", quality, "mobileThumbnail", "mobileBanner", "cardBanner", 
  "mobileCardBanner", logo, "videoUrl", "detailMobileBanner", "detailBanner", 
  "mobileCarouselBanner", subtitles, "trailerUrl", "trailerVttUrl", "spriteUrl", 
  "spriteConfig", "downloadUrl", seasons, "squareThumbnail", "tallTrailerUrl", 
  "mediaType", "xRay"
) VALUES (
  'alapaap-overdrive',
  'Alapaap/Overdrive',
  '/images/alapaap.webp',
  '/images/alapaap-detail.webp',
  'This high-octane performance of “Alapaap / Overdrive” captures the raw rebellion and fleeting freedom of youth. It’s an emotional escape fueled by the reckless energy that ultimately shapes the characters'' journey.',
  '9.8',
  2026,
  '6m',
  ARRAY['Musical', 'Drama', 'Nostalgia', 'Ang Huling El Bimbo'],
  'PG-13',
  null,
  false,
  null,
  false,
  null,
  null,
  null,
  '/images/alapaap-detail-mobile.webp',
  '/images/alapaap.webp',
  null,
  '/images/alapaap-logo.webp',
  'https://boycanad.github.io/stream-storage-3/Alapaap/index.m3u8',
  null,
  null,
  null,
  null,
  'https://boycanad.github.io/stream-storage-2/Alapaap_TRAILER_MOBILE.mp4',
  'https://boycanad.github.io/stream-storage-2/Alapaap_TRAILER_MOBILE.vtt',
  null,
  null,
  null,
  null,
  '/images/clips/square/Alapaap.webp',
  'https://res.cloudinary.com/dtzphltjc/video/upload/f_mp4,vc_h264,ac_aac/v1776811438/Alapaap-tall_nuyyqm.mp4',
  'movie',
  null
) ON CONFLICT (id) DO UPDATE SET 
  title = EXCLUDED.title,
  thumbnail = EXCLUDED.thumbnail,
  banner = EXCLUDED.banner,
  description = EXCLUDED.description,
  rating = EXCLUDED.rating,
  year = EXCLUDED.year,
  duration = EXCLUDED.duration,
  genre = EXCLUDED.genre,
  "ageRating" = EXCLUDED."ageRating",
  "contentWarnings" = EXCLUDED."contentWarnings",
  "isOriginal" = EXCLUDED."isOriginal",
  progress = EXCLUDED.progress,
  "desktopOnly" = EXCLUDED."desktopOnly",
  "streamStatus" = EXCLUDED."streamStatus",
  quality = EXCLUDED.quality,
  "mobileThumbnail" = EXCLUDED."mobileThumbnail",
  "mobileBanner" = EXCLUDED."mobileBanner",
  "cardBanner" = EXCLUDED."cardBanner",
  "mobileCardBanner" = EXCLUDED."mobileCardBanner",
  logo = EXCLUDED.logo,
  "videoUrl" = EXCLUDED."videoUrl",
  "detailMobileBanner" = EXCLUDED."detailMobileBanner",
  "detailBanner" = EXCLUDED."detailBanner",
  "mobileCarouselBanner" = EXCLUDED."mobileCarouselBanner",
  subtitles = EXCLUDED.subtitles,
  "trailerUrl" = EXCLUDED."trailerUrl",
  "trailerVttUrl" = EXCLUDED."trailerVttUrl",
  "spriteUrl" = EXCLUDED."spriteUrl",
  "spriteConfig" = EXCLUDED."spriteConfig",
  "downloadUrl" = EXCLUDED."downloadUrl",
  seasons = EXCLUDED.seasons,
  "squareThumbnail" = EXCLUDED."squareThumbnail",
  "tallTrailerUrl" = EXCLUDED."tallTrailerUrl",
  "mediaType" = EXCLUDED."mediaType",
  "xRay" = EXCLUDED."xRay";


INSERT INTO movies (
  id, title, thumbnail, banner, description, rating, year, duration, genre, 
  "ageRating", "contentWarnings", "isOriginal", progress, "desktopOnly", 
  "streamStatus", quality, "mobileThumbnail", "mobileBanner", "cardBanner", 
  "mobileCardBanner", logo, "videoUrl", "detailMobileBanner", "detailBanner", 
  "mobileCarouselBanner", subtitles, "trailerUrl", "trailerVttUrl", "spriteUrl", 
  "spriteConfig", "downloadUrl", seasons, "squareThumbnail", "tallTrailerUrl", 
  "mediaType", "xRay"
) VALUES (
  'spoliarium-graduation',
  'Spoliarium/Graduation',
  '/images/spoliarium.webp',
  '/images/spoliarium-detail.webp',
  'The “Spoliarium/Graduation” sequence moves from the visceral trauma of Joy’s stolen innocence to the bitter irony of celebration. Marko’s ill-timed confession of love serves as a heartbreaking reminder of a future already shattered by the darkness preceding it.',
  '9.9',
  2026,
  '5m',
  ARRAY['Musical', 'Drama', 'Nostalgia', 'Ang Huling El Bimbo'],
  'PG-13',
  null,
  false,
  null,
  false,
  null,
  null,
  null,
  '/images/spoliarium-detail-mobile.webp',
  '/images/spoliarium.webp',
  null,
  '/images/spoliarium-logo.webp',
  'https://boycanad.github.io/stream-storage-3/Spoliarium/index.m3u8',
  null,
  null,
  null,
  null,
  'https://boycanad.github.io/stream-storage-2/Spoliarium_TRAILER_MOBILE.mp4',
  'https://boycanad.github.io/stream-storage-2/Spoliarium_TRAILER_MOBILE.vtt',
  null,
  null,
  null,
  null,
  '/images/clips/square/Spoliairum.webp',
  'https://res.cloudinary.com/dtzphltjc/video/upload/f_mp4,vc_h264,ac_aac/v1776811337/Spoliarium-tall_huygnl.mp4',
  'movie',
  null
) ON CONFLICT (id) DO UPDATE SET 
  title = EXCLUDED.title,
  thumbnail = EXCLUDED.thumbnail,
  banner = EXCLUDED.banner,
  description = EXCLUDED.description,
  rating = EXCLUDED.rating,
  year = EXCLUDED.year,
  duration = EXCLUDED.duration,
  genre = EXCLUDED.genre,
  "ageRating" = EXCLUDED."ageRating",
  "contentWarnings" = EXCLUDED."contentWarnings",
  "isOriginal" = EXCLUDED."isOriginal",
  progress = EXCLUDED.progress,
  "desktopOnly" = EXCLUDED."desktopOnly",
  "streamStatus" = EXCLUDED."streamStatus",
  quality = EXCLUDED.quality,
  "mobileThumbnail" = EXCLUDED."mobileThumbnail",
  "mobileBanner" = EXCLUDED."mobileBanner",
  "cardBanner" = EXCLUDED."cardBanner",
  "mobileCardBanner" = EXCLUDED."mobileCardBanner",
  logo = EXCLUDED.logo,
  "videoUrl" = EXCLUDED."videoUrl",
  "detailMobileBanner" = EXCLUDED."detailMobileBanner",
  "detailBanner" = EXCLUDED."detailBanner",
  "mobileCarouselBanner" = EXCLUDED."mobileCarouselBanner",
  subtitles = EXCLUDED.subtitles,
  "trailerUrl" = EXCLUDED."trailerUrl",
  "trailerVttUrl" = EXCLUDED."trailerVttUrl",
  "spriteUrl" = EXCLUDED."spriteUrl",
  "spriteConfig" = EXCLUDED."spriteConfig",
  "downloadUrl" = EXCLUDED."downloadUrl",
  seasons = EXCLUDED.seasons,
  "squareThumbnail" = EXCLUDED."squareThumbnail",
  "tallTrailerUrl" = EXCLUDED."tallTrailerUrl",
  "mediaType" = EXCLUDED."mediaType",
  "xRay" = EXCLUDED."xRay";


INSERT INTO movies (
  id, title, thumbnail, banner, description, rating, year, duration, genre, 
  "ageRating", "contentWarnings", "isOriginal", progress, "desktopOnly", 
  "streamStatus", quality, "mobileThumbnail", "mobileBanner", "cardBanner", 
  "mobileCardBanner", logo, "videoUrl", "detailMobileBanner", "detailBanner", 
  "mobileCarouselBanner", subtitles, "trailerUrl", "trailerVttUrl", "spriteUrl", 
  "spriteConfig", "downloadUrl", seasons, "squareThumbnail", "tallTrailerUrl", 
  "mediaType", "xRay"
) VALUES (
  'pare-ko',
  'Pare Ko',
  '/images/pare-ko.webp',
  '/images/pare-ko-detail.webp',
  'This high-energy ROTC sequence transforms military drills into a vibrant spectacle of brotherhood. Set to the iconic **“Pare Ko,”** it balances sharp choreography with the raw “friendzone” angst that defines the bond between the three leads.',
  '9.6',
  2026,
  '6m',
  ARRAY['Musical', 'Drama', 'Nostalgia', 'Ang Huling El Bimbo'],
  'PG-13',
  null,
  false,
  null,
  false,
  null,
  null,
  null,
  '/images/pare-ko-detail-mobile.webp',
  '/images/pare-ko.webp',
  null,
  '/images/pare-ko-logo.webp',
  'https://boycanad.github.io/stream-storage-3/PareKo/index.m3u8',
  null,
  null,
  null,
  null,
  'https://boycanad.github.io/stream-storage-2/PareKo_TRAILER_MOBILE.mp4',
  'https://boycanad.github.io/stream-storage-2/PareKo_TRAILER_MOBILE.vtt',
  null,
  null,
  null,
  null,
  '/images/clips/square/PareKo.webp',
  'https://res.cloudinary.com/dtzphltjc/video/upload/f_mp4,vc_h264,ac_aac/v1776811352/PareKo-tall_xrdjxa.mp4',
  'movie',
  null
) ON CONFLICT (id) DO UPDATE SET 
  title = EXCLUDED.title,
  thumbnail = EXCLUDED.thumbnail,
  banner = EXCLUDED.banner,
  description = EXCLUDED.description,
  rating = EXCLUDED.rating,
  year = EXCLUDED.year,
  duration = EXCLUDED.duration,
  genre = EXCLUDED.genre,
  "ageRating" = EXCLUDED."ageRating",
  "contentWarnings" = EXCLUDED."contentWarnings",
  "isOriginal" = EXCLUDED."isOriginal",
  progress = EXCLUDED.progress,
  "desktopOnly" = EXCLUDED."desktopOnly",
  "streamStatus" = EXCLUDED."streamStatus",
  quality = EXCLUDED.quality,
  "mobileThumbnail" = EXCLUDED."mobileThumbnail",
  "mobileBanner" = EXCLUDED."mobileBanner",
  "cardBanner" = EXCLUDED."cardBanner",
  "mobileCardBanner" = EXCLUDED."mobileCardBanner",
  logo = EXCLUDED.logo,
  "videoUrl" = EXCLUDED."videoUrl",
  "detailMobileBanner" = EXCLUDED."detailMobileBanner",
  "detailBanner" = EXCLUDED."detailBanner",
  "mobileCarouselBanner" = EXCLUDED."mobileCarouselBanner",
  subtitles = EXCLUDED.subtitles,
  "trailerUrl" = EXCLUDED."trailerUrl",
  "trailerVttUrl" = EXCLUDED."trailerVttUrl",
  "spriteUrl" = EXCLUDED."spriteUrl",
  "spriteConfig" = EXCLUDED."spriteConfig",
  "downloadUrl" = EXCLUDED."downloadUrl",
  seasons = EXCLUDED.seasons,
  "squareThumbnail" = EXCLUDED."squareThumbnail",
  "tallTrailerUrl" = EXCLUDED."tallTrailerUrl",
  "mediaType" = EXCLUDED."mediaType",
  "xRay" = EXCLUDED."xRay";


INSERT INTO movies (
  id, title, thumbnail, banner, description, rating, year, duration, genre, 
  "ageRating", "contentWarnings", "isOriginal", progress, "desktopOnly", 
  "streamStatus", quality, "mobileThumbnail", "mobileBanner", "cardBanner", 
  "mobileCardBanner", logo, "videoUrl", "detailMobileBanner", "detailBanner", 
  "mobileCarouselBanner", subtitles, "trailerUrl", "trailerVttUrl", "spriteUrl", 
  "spriteConfig", "downloadUrl", seasons, "squareThumbnail", "tallTrailerUrl", 
  "mediaType", "xRay"
) VALUES (
  'tama-ka-ligaya',
  'Tama Ka/Ligaya',
  '/images/tama-ka.webp',
  '/images/tama-ka-detail.webp',
  'The “Tama Ka / Ligaya” mashup contrasts the finality of a breakup with the warmth of nostalgia. It masterfully captures the bittersweet irony of moving on while still clinging to a lost happiness.',
  '9.8',
  2026,
  '4m',
  ARRAY['Musical', 'Drama', 'Nostalgia', 'Ang Huling El Bimbo'],
  'PG-13',
  null,
  false,
  null,
  false,
  null,
  null,
  '/images/tama-ka-mobile.webp',
  '/images/tama-ka-detail-mobile.webp',
  '/images/tama-ka.webp',
  '/images/tama-ka-mobile.webp',
  '/images/tama-ka-logo.webp',
  'https://boycanad.github.io/stream-storage-3/TamaKa/index.m3u8',
  null,
  null,
  null,
  null,
  'https://boycanad.github.io/stream-storage-2/TamaKa_TRAILER_MOBILE.mp4',
  'https://boycanad.github.io/stream-storage-2/TamaKa_TRAILER_MOBILE.vtt',
  null,
  null,
  null,
  null,
  '/images/clips/square/TamaKa.webp',
  'https://res.cloudinary.com/dtzphltjc/video/upload/f_mp4,vc_h264,ac_aac/v1776811324/TamaKa-tall_uficjc.mp4',
  'movie',
  null
) ON CONFLICT (id) DO UPDATE SET 
  title = EXCLUDED.title,
  thumbnail = EXCLUDED.thumbnail,
  banner = EXCLUDED.banner,
  description = EXCLUDED.description,
  rating = EXCLUDED.rating,
  year = EXCLUDED.year,
  duration = EXCLUDED.duration,
  genre = EXCLUDED.genre,
  "ageRating" = EXCLUDED."ageRating",
  "contentWarnings" = EXCLUDED."contentWarnings",
  "isOriginal" = EXCLUDED."isOriginal",
  progress = EXCLUDED.progress,
  "desktopOnly" = EXCLUDED."desktopOnly",
  "streamStatus" = EXCLUDED."streamStatus",
  quality = EXCLUDED.quality,
  "mobileThumbnail" = EXCLUDED."mobileThumbnail",
  "mobileBanner" = EXCLUDED."mobileBanner",
  "cardBanner" = EXCLUDED."cardBanner",
  "mobileCardBanner" = EXCLUDED."mobileCardBanner",
  logo = EXCLUDED.logo,
  "videoUrl" = EXCLUDED."videoUrl",
  "detailMobileBanner" = EXCLUDED."detailMobileBanner",
  "detailBanner" = EXCLUDED."detailBanner",
  "mobileCarouselBanner" = EXCLUDED."mobileCarouselBanner",
  subtitles = EXCLUDED.subtitles,
  "trailerUrl" = EXCLUDED."trailerUrl",
  "trailerVttUrl" = EXCLUDED."trailerVttUrl",
  "spriteUrl" = EXCLUDED."spriteUrl",
  "spriteConfig" = EXCLUDED."spriteConfig",
  "downloadUrl" = EXCLUDED."downloadUrl",
  seasons = EXCLUDED.seasons,
  "squareThumbnail" = EXCLUDED."squareThumbnail",
  "tallTrailerUrl" = EXCLUDED."tallTrailerUrl",
  "mediaType" = EXCLUDED."mediaType",
  "xRay" = EXCLUDED."xRay";


INSERT INTO movies (
  id, title, thumbnail, banner, description, rating, year, duration, genre, 
  "ageRating", "contentWarnings", "isOriginal", progress, "desktopOnly", 
  "streamStatus", quality, "mobileThumbnail", "mobileBanner", "cardBanner", 
  "mobileCardBanner", logo, "videoUrl", "detailMobileBanner", "detailBanner", 
  "mobileCarouselBanner", subtitles, "trailerUrl", "trailerVttUrl", "spriteUrl", 
  "spriteConfig", "downloadUrl", seasons, "squareThumbnail", "tallTrailerUrl", 
  "mediaType", "xRay"
) VALUES (
  'ang-huling-el-bimbo',
  'Ang Huling El Bimbo',
  '/images/huling-el-bimbo.webp',
  '/images/huling-el-bimbo-detail.webp',
  'The heart-wrenching “Ang Huling El Bimbo” finale mirrors a graceful past against a tragic present. As a tribute to Joy, it captures the regret of a friendship ended too soon, closing the story with the haunting beauty of a dream that can never be reclaimed.',
  '9.9',
  2026,
  '11m',
  ARRAY['Musical', 'Drama', 'Nostalgia', 'Ang Huling El Bimbo'],
  'PG-13',
  null,
  false,
  null,
  false,
  null,
  null,
  '/images/huling-el-bimbo-mobile.webp',
  '/images/huling-el-bimbo-detail-mobile.webp',
  '/images/huling-el-bimbo.webp',
  '/images/huling-el-bimbo-mobile.webp',
  '/images/huling-el-bimbo-logo.webp',
  'https://boycanad.github.io/stream-storage-3/ElBimbo/index.m3u8',
  null,
  null,
  null,
  null,
  'https://boycanad.github.io/stream-storage-2/ElBimbo_TRAILER_MOBILE.mp4',
  'https://boycanad.github.io/stream-storage-2/ElBimbo_TRAILER_MOBILE.vtt',
  null,
  null,
  null,
  null,
  '/images/clips/square/AngHulingElBimbo.webp',
  'https://res.cloudinary.com/dtzphltjc/video/upload/f_mp4,vc_h264,ac_aac/v1776811427/ElBimbo-tall_aixrsg.mp4',
  'movie',
  null
) ON CONFLICT (id) DO UPDATE SET 
  title = EXCLUDED.title,
  thumbnail = EXCLUDED.thumbnail,
  banner = EXCLUDED.banner,
  description = EXCLUDED.description,
  rating = EXCLUDED.rating,
  year = EXCLUDED.year,
  duration = EXCLUDED.duration,
  genre = EXCLUDED.genre,
  "ageRating" = EXCLUDED."ageRating",
  "contentWarnings" = EXCLUDED."contentWarnings",
  "isOriginal" = EXCLUDED."isOriginal",
  progress = EXCLUDED.progress,
  "desktopOnly" = EXCLUDED."desktopOnly",
  "streamStatus" = EXCLUDED."streamStatus",
  quality = EXCLUDED.quality,
  "mobileThumbnail" = EXCLUDED."mobileThumbnail",
  "mobileBanner" = EXCLUDED."mobileBanner",
  "cardBanner" = EXCLUDED."cardBanner",
  "mobileCardBanner" = EXCLUDED."mobileCardBanner",
  logo = EXCLUDED.logo,
  "videoUrl" = EXCLUDED."videoUrl",
  "detailMobileBanner" = EXCLUDED."detailMobileBanner",
  "detailBanner" = EXCLUDED."detailBanner",
  "mobileCarouselBanner" = EXCLUDED."mobileCarouselBanner",
  subtitles = EXCLUDED.subtitles,
  "trailerUrl" = EXCLUDED."trailerUrl",
  "trailerVttUrl" = EXCLUDED."trailerVttUrl",
  "spriteUrl" = EXCLUDED."spriteUrl",
  "spriteConfig" = EXCLUDED."spriteConfig",
  "downloadUrl" = EXCLUDED."downloadUrl",
  seasons = EXCLUDED.seasons,
  "squareThumbnail" = EXCLUDED."squareThumbnail",
  "tallTrailerUrl" = EXCLUDED."tallTrailerUrl",
  "mediaType" = EXCLUDED."mediaType",
  "xRay" = EXCLUDED."xRay";


INSERT INTO movies (
  id, title, thumbnail, banner, description, rating, year, duration, genre, 
  "ageRating", "contentWarnings", "isOriginal", progress, "desktopOnly", 
  "streamStatus", quality, "mobileThumbnail", "mobileBanner", "cardBanner", 
  "mobileCardBanner", logo, "videoUrl", "detailMobileBanner", "detailBanner", 
  "mobileCarouselBanner", subtitles, "trailerUrl", "trailerVttUrl", "spriteUrl", 
  "spriteConfig", "downloadUrl", seasons, "squareThumbnail", "tallTrailerUrl", 
  "mediaType", "xRay"
) VALUES (
  'bukang-liwayway-takipsilim',
  'Bukang-Liwayway Hanggang Takipsilim',
  '/images/MBLHTS.webp',
  '/images/MBLHTS-banner.webp',
  'A profound documentary exploring the journey of self-discovery and the beauty of transient moments from dawn until dusk.',
  '9.5',
  2026,
  'Documentary',
  ARRAY['Documentary', 'STEM'],
  'G',
  null,
  false,
  null,
  false,
  null,
  null,
  '/images/MBLHTS-mobile.webp',
  '/images/MBLHTS-banner.webp',
  null,
  null,
  '/images/BUKANG-LOGO.webp',
  null,
  null,
  null,
  null,
  null,
  'https://github.com/BoyCanad/stream-storage-2/raw/refs/heads/main/BLHT-trailer.mp4',
  'https://boycanad.github.io/stream-storage-2/BLHT-trailer.vtt',
  null,
  null,
  null,
  null,
  '/images/clips/square/BLHTS.webp',
  'https://res.cloudinary.com/dtzphltjc/video/upload/f_mp4,vc_h264,ac_aac/v1776810731/BLHT-tall_uinnb3.mp4',
  'movie',
  null
) ON CONFLICT (id) DO UPDATE SET 
  title = EXCLUDED.title,
  thumbnail = EXCLUDED.thumbnail,
  banner = EXCLUDED.banner,
  description = EXCLUDED.description,
  rating = EXCLUDED.rating,
  year = EXCLUDED.year,
  duration = EXCLUDED.duration,
  genre = EXCLUDED.genre,
  "ageRating" = EXCLUDED."ageRating",
  "contentWarnings" = EXCLUDED."contentWarnings",
  "isOriginal" = EXCLUDED."isOriginal",
  progress = EXCLUDED.progress,
  "desktopOnly" = EXCLUDED."desktopOnly",
  "streamStatus" = EXCLUDED."streamStatus",
  quality = EXCLUDED.quality,
  "mobileThumbnail" = EXCLUDED."mobileThumbnail",
  "mobileBanner" = EXCLUDED."mobileBanner",
  "cardBanner" = EXCLUDED."cardBanner",
  "mobileCardBanner" = EXCLUDED."mobileCardBanner",
  logo = EXCLUDED.logo,
  "videoUrl" = EXCLUDED."videoUrl",
  "detailMobileBanner" = EXCLUDED."detailMobileBanner",
  "detailBanner" = EXCLUDED."detailBanner",
  "mobileCarouselBanner" = EXCLUDED."mobileCarouselBanner",
  subtitles = EXCLUDED.subtitles,
  "trailerUrl" = EXCLUDED."trailerUrl",
  "trailerVttUrl" = EXCLUDED."trailerVttUrl",
  "spriteUrl" = EXCLUDED."spriteUrl",
  "spriteConfig" = EXCLUDED."spriteConfig",
  "downloadUrl" = EXCLUDED."downloadUrl",
  seasons = EXCLUDED.seasons,
  "squareThumbnail" = EXCLUDED."squareThumbnail",
  "tallTrailerUrl" = EXCLUDED."tallTrailerUrl",
  "mediaType" = EXCLUDED."mediaType",
  "xRay" = EXCLUDED."xRay";


INSERT INTO movies (
  id, title, thumbnail, banner, description, rating, year, duration, genre, 
  "ageRating", "contentWarnings", "isOriginal", progress, "desktopOnly", 
  "streamStatus", quality, "mobileThumbnail", "mobileBanner", "cardBanner", 
  "mobileCardBanner", logo, "videoUrl", "detailMobileBanner", "detailBanner", 
  "mobileCarouselBanner", subtitles, "trailerUrl", "trailerVttUrl", "spriteUrl", 
  "spriteConfig", "downloadUrl", seasons, "squareThumbnail", "tallTrailerUrl", 
  "mediaType", "xRay"
) VALUES (
  'a-day-in-my-life-stem',
  'A Day In My Life as a STEM Student',
  '/images/ADIML.webp',
  '/images/ADML-banner.webp',
  'An authentic look into the rigorous yet rewarding daily life of a STEM student, capturing the balance between academic challenges and personal growth.',
  '9.3',
  2026,
  'Vlog',
  ARRAY['Classroom', 'Documentary', 'STEM'],
  'G',
  null,
  false,
  null,
  false,
  null,
  null,
  '/images/ADIML-mobile.webp',
  '/images/ADIML-banner-mobile.webp',
  null,
  null,
  '/images/ADIML-LOGO.webp',
  null,
  null,
  null,
  null,
  null,
  'https://github.com/BoyCanad/stream-storage-2/raw/refs/heads/main/ADIML-trailer.mp4',
  'https://boycanad.github.io/stream-storage-2/ADIML-trailer.vtt',
  null,
  null,
  null,
  null,
  '/images/clips/square/ADIML.webp',
  'https://res.cloudinary.com/dtzphltjc/video/upload/f_mp4,vc_h264,ac_aac/v1776810709/ADIML-tall_rtdvt5.mp4',
  'movie',
  null
) ON CONFLICT (id) DO UPDATE SET 
  title = EXCLUDED.title,
  thumbnail = EXCLUDED.thumbnail,
  banner = EXCLUDED.banner,
  description = EXCLUDED.description,
  rating = EXCLUDED.rating,
  year = EXCLUDED.year,
  duration = EXCLUDED.duration,
  genre = EXCLUDED.genre,
  "ageRating" = EXCLUDED."ageRating",
  "contentWarnings" = EXCLUDED."contentWarnings",
  "isOriginal" = EXCLUDED."isOriginal",
  progress = EXCLUDED.progress,
  "desktopOnly" = EXCLUDED."desktopOnly",
  "streamStatus" = EXCLUDED."streamStatus",
  quality = EXCLUDED.quality,
  "mobileThumbnail" = EXCLUDED."mobileThumbnail",
  "mobileBanner" = EXCLUDED."mobileBanner",
  "cardBanner" = EXCLUDED."cardBanner",
  "mobileCardBanner" = EXCLUDED."mobileCardBanner",
  logo = EXCLUDED.logo,
  "videoUrl" = EXCLUDED."videoUrl",
  "detailMobileBanner" = EXCLUDED."detailMobileBanner",
  "detailBanner" = EXCLUDED."detailBanner",
  "mobileCarouselBanner" = EXCLUDED."mobileCarouselBanner",
  subtitles = EXCLUDED.subtitles,
  "trailerUrl" = EXCLUDED."trailerUrl",
  "trailerVttUrl" = EXCLUDED."trailerVttUrl",
  "spriteUrl" = EXCLUDED."spriteUrl",
  "spriteConfig" = EXCLUDED."spriteConfig",
  "downloadUrl" = EXCLUDED."downloadUrl",
  seasons = EXCLUDED.seasons,
  "squareThumbnail" = EXCLUDED."squareThumbnail",
  "tallTrailerUrl" = EXCLUDED."tallTrailerUrl",
  "mediaType" = EXCLUDED."mediaType",
  "xRay" = EXCLUDED."xRay";


INSERT INTO movies (
  id, title, thumbnail, banner, description, rating, year, duration, genre, 
  "ageRating", "contentWarnings", "isOriginal", progress, "desktopOnly", 
  "streamStatus", quality, "mobileThumbnail", "mobileBanner", "cardBanner", 
  "mobileCardBanner", logo, "videoUrl", "detailMobileBanner", "detailBanner", 
  "mobileCarouselBanner", subtitles, "trailerUrl", "trailerVttUrl", "spriteUrl", 
  "spriteConfig", "downloadUrl", seasons, "squareThumbnail", "tallTrailerUrl", 
  "mediaType", "xRay"
) VALUES (
  't1',
  '11 STEM A SY 2025-2026',
  '/images/stem-a-archive.webp',
  '/images/stem-a-archive.webp',
  'A digital archive documenting the journey, memories, and milestones of 11-STEM A for the School Year 2025-2026.',
  '9.9',
  2026,
  'Archive',
  ARRAY['Classroom', 'Documentary', 'STEM'],
  'G',
  null,
  false,
  null,
  false,
  null,
  null,
  '/images/stem-a-archive-mobile.webp',
  '/images/stem-a-mobile-carousel.webp',
  null,
  null,
  '/images/stem-a-logo.webp',
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  'show',
  null
) ON CONFLICT (id) DO UPDATE SET 
  title = EXCLUDED.title,
  thumbnail = EXCLUDED.thumbnail,
  banner = EXCLUDED.banner,
  description = EXCLUDED.description,
  rating = EXCLUDED.rating,
  year = EXCLUDED.year,
  duration = EXCLUDED.duration,
  genre = EXCLUDED.genre,
  "ageRating" = EXCLUDED."ageRating",
  "contentWarnings" = EXCLUDED."contentWarnings",
  "isOriginal" = EXCLUDED."isOriginal",
  progress = EXCLUDED.progress,
  "desktopOnly" = EXCLUDED."desktopOnly",
  "streamStatus" = EXCLUDED."streamStatus",
  quality = EXCLUDED.quality,
  "mobileThumbnail" = EXCLUDED."mobileThumbnail",
  "mobileBanner" = EXCLUDED."mobileBanner",
  "cardBanner" = EXCLUDED."cardBanner",
  "mobileCardBanner" = EXCLUDED."mobileCardBanner",
  logo = EXCLUDED.logo,
  "videoUrl" = EXCLUDED."videoUrl",
  "detailMobileBanner" = EXCLUDED."detailMobileBanner",
  "detailBanner" = EXCLUDED."detailBanner",
  "mobileCarouselBanner" = EXCLUDED."mobileCarouselBanner",
  subtitles = EXCLUDED.subtitles,
  "trailerUrl" = EXCLUDED."trailerUrl",
  "trailerVttUrl" = EXCLUDED."trailerVttUrl",
  "spriteUrl" = EXCLUDED."spriteUrl",
  "spriteConfig" = EXCLUDED."spriteConfig",
  "downloadUrl" = EXCLUDED."downloadUrl",
  seasons = EXCLUDED.seasons,
  "squareThumbnail" = EXCLUDED."squareThumbnail",
  "tallTrailerUrl" = EXCLUDED."tallTrailerUrl",
  "mediaType" = EXCLUDED."mediaType",
  "xRay" = EXCLUDED."xRay";


INSERT INTO movies (
  id, title, thumbnail, banner, description, rating, year, duration, genre, 
  "ageRating", "contentWarnings", "isOriginal", progress, "desktopOnly", 
  "streamStatus", quality, "mobileThumbnail", "mobileBanner", "cardBanner", 
  "mobileCardBanner", logo, "videoUrl", "detailMobileBanner", "detailBanner", 
  "mobileCarouselBanner", subtitles, "trailerUrl", "trailerVttUrl", "spriteUrl", 
  "spriteConfig", "downloadUrl", seasons, "squareThumbnail", "tallTrailerUrl", 
  "mediaType", "xRay"
) VALUES (
  'beyond-the-last-dance',
  'Beyond The Last Dance',
  '/images/BTLD.webp',
  '/images/BTLD-banner.webp',
  'A behind-the-scenes look at the creative journey, the challenges, and the heart that went into crafting the multi-awarded musical masterpiece, Ang Huling El Bimbo.',
  '10.0',
  2026,
  '1h 15m',
  ARRAY['Documentary', 'Behind the Scenes', 'Ang Huling El Bimbo'],
  'PG-13',
  null,
  true,
  null,
  false,
  null,
  null,
  '/images/BTLD-mobile.webp',
  '/images/BTLD-mobile-banner.webp',
  '/images/BTLD.webp',
  '/images/BTLD-mobile.webp',
  '/images/BTLD-logo.webp',
  '',
  null,
  null,
  null,
  null,
  'https://github.com/BoyCanad/stream-storage-2/raw/refs/heads/main/BTLD-trailer.mp4',
  'https://boycanad.github.io/stream-storage-2/BTLD-trailer.vtt',
  null,
  null,
  null,
  null,
  '/images/clips/square/BTLD.webp',
  'https://res.cloudinary.com/dtzphltjc/video/upload/f_mp4,vc_h264,ac_aac/v1776810741/BTLD-tall_abf3st.mp4',
  'show',
  null
) ON CONFLICT (id) DO UPDATE SET 
  title = EXCLUDED.title,
  thumbnail = EXCLUDED.thumbnail,
  banner = EXCLUDED.banner,
  description = EXCLUDED.description,
  rating = EXCLUDED.rating,
  year = EXCLUDED.year,
  duration = EXCLUDED.duration,
  genre = EXCLUDED.genre,
  "ageRating" = EXCLUDED."ageRating",
  "contentWarnings" = EXCLUDED."contentWarnings",
  "isOriginal" = EXCLUDED."isOriginal",
  progress = EXCLUDED.progress,
  "desktopOnly" = EXCLUDED."desktopOnly",
  "streamStatus" = EXCLUDED."streamStatus",
  quality = EXCLUDED.quality,
  "mobileThumbnail" = EXCLUDED."mobileThumbnail",
  "mobileBanner" = EXCLUDED."mobileBanner",
  "cardBanner" = EXCLUDED."cardBanner",
  "mobileCardBanner" = EXCLUDED."mobileCardBanner",
  logo = EXCLUDED.logo,
  "videoUrl" = EXCLUDED."videoUrl",
  "detailMobileBanner" = EXCLUDED."detailMobileBanner",
  "detailBanner" = EXCLUDED."detailBanner",
  "mobileCarouselBanner" = EXCLUDED."mobileCarouselBanner",
  subtitles = EXCLUDED.subtitles,
  "trailerUrl" = EXCLUDED."trailerUrl",
  "trailerVttUrl" = EXCLUDED."trailerVttUrl",
  "spriteUrl" = EXCLUDED."spriteUrl",
  "spriteConfig" = EXCLUDED."spriteConfig",
  "downloadUrl" = EXCLUDED."downloadUrl",
  seasons = EXCLUDED.seasons,
  "squareThumbnail" = EXCLUDED."squareThumbnail",
  "tallTrailerUrl" = EXCLUDED."tallTrailerUrl",
  "mediaType" = EXCLUDED."mediaType",
  "xRay" = EXCLUDED."xRay";


INSERT INTO movies (
  id, title, thumbnail, banner, description, rating, year, duration, genre, 
  "ageRating", "contentWarnings", "isOriginal", progress, "desktopOnly", 
  "streamStatus", quality, "mobileThumbnail", "mobileBanner", "cardBanner", 
  "mobileCardBanner", logo, "videoUrl", "detailMobileBanner", "detailBanner", 
  "mobileCarouselBanner", subtitles, "trailerUrl", "trailerVttUrl", "spriteUrl", 
  "spriteConfig", "downloadUrl", seasons, "squareThumbnail", "tallTrailerUrl", 
  "mediaType", "xRay"
) VALUES (
  'after-hours',
  'After Hours',
  '/images/after-hours.webp',
  '/images/AFTERHOURS-banner.png',
  'Join us for After Hours, the official 11-STEM A live stream series! Experience real-life moments, candid conversations, and exclusive behind-the-scenes vibes as we document our final journey together.',
  '10.0',
  2026,
  'LIVE',
  ARRAY['Live', 'Documentary', 'Classroom'],
  'PG-13',
  null,
  true,
  null,
  false,
  'live',
  null,
  '/images/after-hours-mobile.webp',
  '/images/AFTERHOURS-banner.png',
  null,
  null,
  '/images/AFTER%20HOURS-logo.png',
  'https://livepeercdn.studio/hls/f8a31biu1b7w4hzw/index.m3u8',
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  '[{"id":"s-april-2026","seasonNumber":1,"title":"Past Stream (April)","episodes":[]}]',
  null,
  null,
  'show',
  null
) ON CONFLICT (id) DO UPDATE SET 
  title = EXCLUDED.title,
  thumbnail = EXCLUDED.thumbnail,
  banner = EXCLUDED.banner,
  description = EXCLUDED.description,
  rating = EXCLUDED.rating,
  year = EXCLUDED.year,
  duration = EXCLUDED.duration,
  genre = EXCLUDED.genre,
  "ageRating" = EXCLUDED."ageRating",
  "contentWarnings" = EXCLUDED."contentWarnings",
  "isOriginal" = EXCLUDED."isOriginal",
  progress = EXCLUDED.progress,
  "desktopOnly" = EXCLUDED."desktopOnly",
  "streamStatus" = EXCLUDED."streamStatus",
  quality = EXCLUDED.quality,
  "mobileThumbnail" = EXCLUDED."mobileThumbnail",
  "mobileBanner" = EXCLUDED."mobileBanner",
  "cardBanner" = EXCLUDED."cardBanner",
  "mobileCardBanner" = EXCLUDED."mobileCardBanner",
  logo = EXCLUDED.logo,
  "videoUrl" = EXCLUDED."videoUrl",
  "detailMobileBanner" = EXCLUDED."detailMobileBanner",
  "detailBanner" = EXCLUDED."detailBanner",
  "mobileCarouselBanner" = EXCLUDED."mobileCarouselBanner",
  subtitles = EXCLUDED.subtitles,
  "trailerUrl" = EXCLUDED."trailerUrl",
  "trailerVttUrl" = EXCLUDED."trailerVttUrl",
  "spriteUrl" = EXCLUDED."spriteUrl",
  "spriteConfig" = EXCLUDED."spriteConfig",
  "downloadUrl" = EXCLUDED."downloadUrl",
  seasons = EXCLUDED.seasons,
  "squareThumbnail" = EXCLUDED."squareThumbnail",
  "tallTrailerUrl" = EXCLUDED."tallTrailerUrl",
  "mediaType" = EXCLUDED."mediaType",
  "xRay" = EXCLUDED."xRay";
